---
- name: Install nginx apt install nodejs
  ansible.builtin.apt:
    pkg:
      - gnupg
- name: Add an Apt signing key to a specific keyring file
  ansible.builtin.apt_key:
    url: https://pgp.mongodb.com/server-7.0.asc
    keyring: /usr/share/keyrings/mongodb-server-7.0.gpg
- name: Install packages and build app
  ansible.builtin.command:
    cmd: touch /etc/apt/sources.list.d/mongodb-org-7.0.list
- name: Install packages and build app
  ansible.builtin.shell:
    cmd: echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
- name: Install packages and build app
  ansible.builtin.command:
    cmd: sudo apt-get update
- name: Install nginx apt install nodejs
  ansible.builtin.apt:
    pkg:
      - mongodb-org
- name: Restart nginx
  ansible.builtin.service:
    name: mongod
    state: restarted
