---
- name: Install nginx
  ansible.builtin.apt:
    pkg:
      - nginx
- name: Copy nginx config file
  ansible.builtin.copy:
    src: files/nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: "0644"
# - name: Copy nginx config file
#   ansible.builtin.copy:
#     src: files/security-headers.conf
#     dest: /etc/nginx/security-headers.conf
#     mode: "0644"
# - name: Copy index.html
#   ansible.builtin.template:
#     src: templates/index.html.j2
#     dest: /usr/share/nginx/html/index.html
#     mode: "0644"
- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
