---
- name: "Playbook Entrypoint"
  hosts: all
  become: true
  become_user: root
  gather_facts: false
  roles:
    - mongodb
    - backend
  tasks:
    - name: Allow all access to tcp port 80
      community.general.ufw:
        rule: allow
        port: "80"
        proto: tcp
    - name: Allow all access to tcp port 443
      community.general.ufw:
        rule: allow
        port: "443"
        proto: tcp
